[package]
name = "world"
description = "World management for Nostalgia server"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
byteorder.workspace = true
nbt.workspace = true